.circleci/config.yml, .github/workflows/go.yml, runner/util_test.go
try to fix https://github.com/cosmtrek/air/issues/87
=> create github action workflow and add IsDir() test case

runner/config.go, runner/config_test.go, version.go
As a result of running `gofmt`, I see a difference in the source, so I send a pull request.
Fixed #81.
=> Run `gofmt -w .`

.github/workflows/go.yml, .goreleaser.yml, Makefile, version.go
resolves #105 
release workflow test
https://github.com/tkms0106/air/runs/1065558109?check_suite_focus=true
=> feat: set airVersion and goVersion with ldflags in release process

.github/workflows/go.yml, Dockerfile, go.mod
Updates the go version to 1.16 to support Apple M1 and embedding.
=> Update go version to 1.16

air_example.toml, runner/config.go, runner/engine.go, runner/engine_test.go, runner/util.go
Adding `ExcludeRegex` to build config, excluding files based on compiled regular expressions. Test included.
=> ExcludeRegex

air_example.toml, runner/config.go, runner/engine.go
Changes:
- add a new option: `follow_symlink`
- able to follow symlink to scan and watch dirs
=> Follow symlink if required

main.go, runner/engine.go, runner/util.go
=> Fix process not being killed on Windows

runner/config.go, runner/engine.go
close  https://github.com/cosmtrek/air/issues/139
=> feat(*):support clear screen when rebuild

runner/engine.go
Closes https://github.com/cosmtrek/air/issues/184
=> Fix no re-build issue when exclude_unchanged is true

runner/util_linux.go
close https://github.com/cosmtrek/air/issues/217
=> fix no such process issue in linux

runner/util.go, runner/util_test.go
close https://github.com/cosmtrek/air/issues/207
=> fix windows arg issue

README.md
May even make it the preferred way of installing.
=> Add `go install` methods to README

runner/util_darwin.go
We need a negative pid here to kill the whole process group.
=> fix interrupt handling on darwin

runner/config.go
=> Revert "Quote `config.Build.Bin` on the UNIX like OS (including WSL)"

runner/engine_test.go
to ensure the feature when file changed need make sure port not confilct
=> Add test cover for rebuild

.github/workflows/build.yml, go.mod, go.sum, runner/engine.go, runner/engine_test.go, runner/util_darwin.go, runner/util_linux.go, runner/util_test.go, runner/util_windows.go
close https://github.com/cosmtrek/air/issues/241
=> Fix  port already used when using dlv to debug go program

runner/engine.go, runner/engine_test.go
close https://github.com/cosmtrek/air/issues/294
=> Fix panic (close of closed channel) after Ctrl + C  

Dockerfile
Update Dockerfile to air able to compile/run go 1.19 projects.
=> Update go version in Dockerfile to 1.19

runner/config.go
Hi there
This package is really helpful in my daily development, thank you.
I was doing some code reading to contribute and found a small typo that I have fixed.
=> fix small typo in runner/config.go

README-zh_cn.md
=> docs: update README-zh_cn.md

README.md
- close: https://github.com/cosmtrek/air/issues/413
=> fix go version in README

go.mod, go.sum, runner/config.go
=> chore: bump version of mergo

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/smoke_test_reuse_job.yml, .github/workflows/smoke_test_window_reust_job.yml, Dockerfile, README.md, go.mod, go.sum
Previous PR for bumping to 1.20 for reference: https://github.com/cosmtrek/air/pull/394.
=> chore: bump Go to 1.21

README.md
- Fix a typo in the README.md file
- Update the command for installing air
- Add a new example for running a project in Docker
- Update the link for "Buy Me A Coffee" in the README.md file
cc @xiantang
=> docs: update README.md file and improve installation instructions

README-zh_tw.md
- Add a new file `README-zh_tw.md`
- Add a new line in `README.md` to include a link to the new file `README-zh_tw.md`
=> feat: add Chinese translation for README.md

runner/config.go, runner/engine.go, runner/engine_test.go
This PR fixes `writeDefaultConfig()` function.
=> Fix "log.Fatalf will exit, defer file.Close() will not run"

.editorconfig, runner/engine.go
Closes https://github.com/cosmtrek/air/issues/379
=> Report success or exit code from run step.

runner/util_windows.go
=> Implement kill delay on Windows

runner/proxy.go
=> Avoid duplicating cors header.

README.md, runner/engine.go, runner/engine_test.go
Fixed a couple of minor typos.
=> fix: typos
