air-verse/air

- runner/utils_darwin.go
Same problem described on #6 happens when running on macOS. 
The code is the same as `utils_linux.go` and it has been tested locally.
> fix: kill process on darwin

- air.conf.example
- runner/config.go
- runner/logger.go
This PR introduces two minors changes to the logger:
**Change 1:** Skip the line feed if the message already ends with one. The problem is that when the running program outputs a log that ends with a line feed, Air is doubling it. This can also be seen here #8 and my attached screenshot. 
**Change 2:** Introduces a new configuration section to customize log messages. Most applications already include time on its log, so it'd be cleaner if we could just ignore this on Air to prevent double time being logged. This can also be seen here #8 and my attached screenshot. 
Bofore PR:
After PR:
> feature: log configuration to customize log output

- .gitignore
- Gopkg.lock
- runner/config.go
- runner/engine.go
- runner/utils_windows.go
This request will fix #7 issue as error referenced there is nil pointer exeption for file which was removed during processing.
Changes:
* Update at `runner/engine.go` fixes case when IDE or another text editor creates temp files(such as Jetbrains Goland create `{file}.___jb_old___`) and removes it right after save during watcher processing.
* Added note for windows users who are trying to use non `.exe` files as bin file, cmd will produce an error, this warning will help windows users to understand what went wrong.
> Several fixes for windows support

- runner/util_linux.go
I observe some processes not killed, after hot-reload.
Right after start:
After some reloads:
I tested this issue on my apps, and on [gin graceful-shutdown](https://github.com/gin-gonic/examples/tree/master/graceful-shutdown/graceful-shutdown) example ([my test code](https://github.com/wsnotify/air-test)).
This addition fixes the problem.
> cmd.Process.Wait

- README.md
CI changed from CircleCI to GitHub Actions.
The CI status badge in `README.md` also needs to be modified accordingly.
> Fix ci badge to GitHub Actions

- .goreleaser.yml
For the purpose of allowing users to download binary directly in release page
cf. https://goreleaser.com/customization/archive/
> ci: Add archives.format setting to .goreleaser.yml

- go.mod
- go.sum
Pulls in fix for https://github.com/creack/pty/issues/96
Was causing `failed to build, error: fork/exec /bin/sh: Setctty set but
Ctty not valid in child`
> chore: bump github.com/creack/pty to v1.1.10

- runner/util.go
This PR fix that air fail to kill process on Windows.
On windows, using "start" command (windows native command) for start process.
The "start" command lunch another child process.
air recognize "start" command's PID but not "start command"'s child process PID.
Therefore fail to kill process.
So used "/b" option not to create child process.
> fix fail to kill process on windows

- air_example.toml
- runner/config.go
- runner/engine.go
- runner/util.go
- runner/util_test.go
Can be enabled with the `[build].exclude_unchanged = true` config option. This is disabled by default.
Editors often save a file even if the contents of the file hasn't changed.
We get the fsnotify event even though there is nothing to be rebuilt in this case.
This PR allows `air` to only rebuild projects if the contents of the files have actually changed.
On startup, we calculate (sha256) checksums of all the watched files, and store them in a cache.
After a file write event, the file contents is hashed to compare it to the previously cached checksum. If the checksums match, the write event is skipped, otherwise the cache is updated and the write event continues.
> feat: Skip write events for unchanged files

- README.md
- main.go
- runner/config.go
- runner/engine.go
Calling `air init` will create the .air.toml based on the default configuration to the current directory. 
This will make it easier to start using a custom config in a new project.
Resolves: #153
> Add init command to create a .air.toml file to the current directory.

- runner/engine.go
This error was shown when trying to delete old `main.exe` file on Windows:
```console
main.go has changed
building...
failed to remove D:\code\flutter\instachat\server\tmp\main.exe, error: remove D:\code\flutter\instachat\server\D:\code\flutter\instachat\server\tmp\main.exe: The filename, directory name, or volume label syntax is incorrect.
running...
```
This patch fixes that error, locally tested.
> Fix Relative Path error on Windows

- go.mod
- go.sum
- runner/config.go
- runner/config_test.go
- runner/engine.go
- runner/util.go
- Make test code ignored by hot reload
- and testdata directory is to be ignored an default
Issue：#127
Why：Since golang is designed to put test files in testdata
https://golang.org/cmd/go/#hdr-Test_packages
c9f5750c6798f4ff974cbffc3156fa5f5e761460  
64084f949353020e8238a69078d1c314e0c8d21c
> Make TestCode ignored by hot reload

- install.sh
When Docker runs over darwin/arm64 usually convert the platform to linux/arm64 just added this platform to allow to run over docker
> Allow linux/arm64 platforms it work with docker over m1

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/smoke_test_reuse_job.yml
- .github/workflows/smoke_test_window_reust_job.yml
- Dockerfile
- Makefile
- go.mod
- go.sum
- smoke_test/check_rebuild/go.mod
- Updated go version from 1.16 to 1.17
- includes Dockerfile, github actions and go.mod.
- The specification of go.mod has been extended to support Module graph pruning since go1.17.
- https://go.dev/doc/go1.17#go-command
- https://go.dev/ref/mod#graph-pruning
- Since the `go get -u` command is deprecated in go1.16, it has been replaced by the `go install` command.
- https://go.dev/doc/go1.16#go-command
ref: https://github.com/cosmtrek/air/issues/205
> Update go 1.17

- runner/util_darwin.go
After removing the `-`, my process can receive the SIGINT correctly.
> Bugfix, get "no such process" with the process id negated

- runner/config.go
fix #175 
The `config.Build.Bin` is used as a parameter for `/bin/sh -c` ([runner/util_linux.go:32](/cosmtrek/air/blob/master/runner/util_linux.go#L32)).
It must be quoted because it may contains white space or other spacial chars.
> Quote `config.Build.Bin` on the UNIX like OS (including WSL)

- air_example.toml
This PR adds an undocumented property to `air_example.toml`
There is an undocumented property inside the codebase for specifying runtime args when executing the binary, it is called `args_bin`.
https://github.com/cosmtrek/air/blob/705822078ed1a98bf367ec28eafb3cae46a9c001/runner/config.go#L38
@xiantang Would appreciate if you can take a look 😄
> Update example air file to document args_bin property

- runner/engine.go
- runner/engine_test.go
- runner/util_darwin.go
- runner/util_linux.go
close https://github.com/cosmtrek/air/issues/278
> try to fix cannot ctrl c when configed kill delay

- README.md
- go.mod
- main.go
- runner/cmdarg_test.go
- runner/config.go
- runner/config_test.go
- runner/engine.go
- runner/engine_test.go
- runner/flag.go
- runner/flag_test.go
- runner/logger.go
- runner/util.go
- runner/util_test.go
Support air config fields as arguments:
if you just want to config build command and run command, you can use like following command without config file:
`air --build.cmd "go build -o bin/api cmd/run.go" --build.bin "./api"`
in toml config define: 
```toml
[build]
full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
```
It will be `air --build.full_bin "APP_ENV=dev APP_USER=air ./tmp/main"`
for slice fields:
```toml
[build]
exclude_regex = ["_test.go"]
```
it will be `air --build.exclude_regex ["_test.go"]`
and so on...
> feat:support command line arguments when user not want use config file

- runner/engine.go
Fixes an issue where the process becomes a zombie because `runBin()` is not calling `wait()`.
see: https://man7.org/linux/man-pages/man2/wait.2.html
Environment
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
```
Steps to reproduce.
```
$ echo '[build]
bin = "app"
cmd = "go build -o app ."
' > .air.toml
$ echo 'package main
import "fmt"
func main() {
fmt.Println("Hello World!")
}
' > main.go
$ go mod init example.com/m
$ air
```
Before
```
$ sed -i -e 's/!/!!/g' main.go # Replace a code.
$ sleep 1 # Wait build.
$ ps f --ppid $(pidof air)
PID TTY      STAT   TIME COMMAND
954786 pts/7    Z      0:00 [sh] <defunct>
954523 pts/7    Z      0:00 [sh] <defunct>
```
After
```
$ sed -i -e 's/!/!!/g' main.go # …
```
> Fix run process become a zombie.

- README-zh_cn.md
- README.md
- runner/config.go
- runner/engine_test.go
- runner/flag.go
- runner/flag_test.go
- runner/util.go
- runner/util_test.go
It seems slice configuration parameters such as `ExcludeDir` cannot be set correctly with command line arguments (nor override default config). The test for `--build.exclude_regex` only passes because the test value corresponds with the default value (set in `defaultConfig`), it's not actually set by the parameter in the test.
I propose to treat the command line arguments for such config parameters as comma separated strings. Setting a value would work as e.g. `--build.exclude_dir "templates,build"`.
> Fix command line argument handling for slice configuration parameters

- air_example.toml
- runner/engine_test.go
I think this regex expression should be "_test\\.go". The '.' character matches any character in regex.
> fixes air_example.toml regex expression

- .github/workflows/build.yml
- runner/config.go
- runner/config_test.go
- runner/engine_test.go
fix https://github.com/cosmtrek/air/issues/304
> Fix update ExcludeRegex to empty not work

- runner/util.go
For example, my project tree look like this:
```
Myproject/
┣ example/
┃ ┣ .air.toml
┃ ┣ go.mod
┃ ┣ go.sum
┃ ┗ main.go
┣ module/
┃ ┣ go.mod
┃ ┗ module.go
┣ .gitignore
┗ go.work
```
I want to run `air` in `example` folder but watch `Myproject` folder. In `.air.toml`, if I set root to `..`, it does not work, I have to set it to `../../Myproject`.
This PR makes support for `..` for root setting.
> Make root config support path like "..", "../..", etc

- runner/config.go
- runner/config_test.go
Fixes https://github.com/cosmtrek/air/issues/320.
This PR fixes an issue where runtime args were being ignored when specifying `full_bin` as opposed to `bin` properties in the config.
> Preserve runtime arguments when using `full_bin`

- air_example.toml
- runner/config.go
- runner/engine.go
- runner/engine_test.go
- runner/util.go
- runner/util_test.go
Useful option to specify individual files to watch. I renamed the `watchDir` function to `watchPath` because it can also handle single files fine (`filepath.Walk` emits a single file if passed a file path).
Fixes: https://github.com/cosmtrek/air/issues/307
Example of it working with a pure `include_dir` and `include_file` config:
> Add `include_file` option

- runner/config.go
Hello guys,
I found a funny bug: I tried to set `stop_on_error = false` in `.air.toml`, but it had no effect. After some debugging, it turns out that the reason is this `mergo` issue: https://github.com/imdario/mergo/issues/129
The problem is that `stop_on_error` is defined as `true` in the `defaultConfig()` function, but `mergo` won't overwrite `true` with `false` from the `defaultPathConfig()` function.
Other solutions are possible, but this looks the simplest without truly introducing `true`/`false`/`undefined` in the concept of air's config for the sake of this one value. Since the `stop_on_error = true` snippet is in the example config file since 2020, and actually before that the default was the current `false` (because the feature was non-existent), I think it would cause a problem …
> Proposed change to fix stop_on_error=false not working in .air.toml

- .github/workflows/build.yml
- .github/workflows/smoke_test.yml
- air_example.toml
- runner/config.go
- runner/engine_test.go
close https://github.com/cosmtrek/air/issues/325
> change build delay to zero

- README.md
I really love Air features. However, when I started dockerize my Golang app, Air did not work. I started some search and found some alternative libs, but I still love Air. So I found a way to make air work with docker-compose (not work by only `docker run` command with `volume` flag for some reason)
For this PR I just add Dockerfile and docker-compose.yaml examples for Docker users who don't want to use air images with fixed Golang version and Linux distro. I think it will help someone who beginner to Air and Docker.
> Add the tutorial for docker users

- runner/config.go
- runner/engine.go
The current clear command fmt.Print("\033[2J") is not completely clear terminal as we can back to it with scroll.
I understand that some people may like to keep the logs and come back with a scroll.
So I added a new param as keep_scroll too.
Also added:
```
Screen: cfgScreen{
ClearOnRebuild: false,
KeepScroll:     false,
},
``` 
So people can see the options
> Feat clear on rebuild

- runner/engine.go
This seems to work on Ubuntu and Windows.
> Log output doesn't show until close #50

- air_example.toml
- runner/config.go
- runner/engine.go
- runner/engine_test.go
> WIP: feat: support executing bin again when bin exit

- runner/engine_test.go
- runner/test_util.go
This test of 078d8ffa29e14c4d462c7ab825188895a32abeaf failed, because of some testing function use the `os.Chdir` but not restore it before exit.
> test: restore the cwd for every test

- air_example.toml
- runner/config.go
- runner/util.go
Hides verbose `air` logging - (which can get in the way of the target program logs).
Defaults to `false` - nothing should change by default, only after a user sets `main_only = true` in the config.
Debug mode overrides this option (if debug mode, show all logs).
Relates to #354 , #201
> Feat: option to silence verbose air logging using `main_only` in config

- air_example.toml
- runner/config.go
- runner/engine.go
- runner/engine_test.go
- runner/logger.go
- runner/watcher.go
I just noticed that reusing `delay` for the poll interval will cause an unintended double delay (first the delay is used as interval, and when a change happened delay is used to wait before building after the change).
Adding a dedicated `poll_interval` parameter allows people to prevent that and apply a more fine-grained configuration.
Also added the new params to the example toml file with some docs which I forgot to do in the initial PR and "fixed" a few linter warnings (if wanted I can of course remove that commit from the PR!).
Thanks again!
> Prevent double delays and add some docs

- runner/util_unix.go
fix: #392
It seems that the same code as macOS will work on most unix.
> build for unix (including freebsd)

- runner/engine.go
- runner/util.go
Air probably shouldn't filter out chmod events, as they're valid filewatcher events dispatched by popular tools specifically for livereload.
This patch fixes Air when using Colima instead of Docker Desktop for Mac, as most users are moving away from Docker Desktop in favor of Colima after the licensing changes.
Related: https://github.com/abiosoft/colima/issues/261#issuecomment-1484677394
> Make air work with Colima

- .goreleaser.yml
* CGO_ENABLED should be set to "0" when application running in alpine linux or it will be failed to start.
> build binaries with CGO_ENABLED=0

- air_example.toml
- runner/config.go
- runner/config_test.go
- runner/engine.go
- runner/engine_test.go
closes #453 
- A new option `pre_cmd` is added to `.air.toml`
- A new option `post_cmd` is added to `.air.tom`
- commands that are in `pre_cmd` will be executed one by one before each build
- commands that are in `post_cmd` will be executed upon exiting (i.e. upon hitting ^C)
> Pre & Post commands 

- runner/engine.go
Hi maintainers, this PR fixes the behavior that air duplicates processses when multiple buildRuns run simultaneously.
Closes #404, Closes #421, Closes #426.
To reproduce issue:
main.go
```go
package main
import (
"log"
"net/http"
"os"
)
func main() {
http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
w.Write([]byte("Hello World!"))
})
log.Print(os.Getpid(), " Starting server...")
if err := http.ListenAndServe(":8080", nil); err != nil {
log.Fatal(os.Getpid(), err)
}
}
```
Run `air -d` and save a file multiple times in a short period of time, then air executes multiple processes.
This behavior appears from v1.41.0, and seems to be brought by the following pull request.
- #363 
I looked into what was making the difference, and it seems that the following code that was in …
> fix: Prevent duplicate processes when multiple buildRuns run simultaneously

- main.go
- runner/config.go
- version.go
close https://github.com/cosmtrek/air/issues/434
> fallback to buildinfo when airversion and goversion is empty

- main.go
- runner/config_test.go
- runner/engine_test.go
- runner/flag_test.go
- runner/util_test.go
- Remove the `runArgs` variable
- Change the way `flag.CommandLine.Parse` is called
- Modify the `TestBinCmdPath` function
- Modify the `TestConfigWithRuntimeArgs` function
- Modify the `TestCtrlCWhenHaveKillDelay` function
- Modify the `include_file` value in the `TestCtrlCWhenHaveKillDelay` function
- Modify the `include_file` value in the `TestConfigRuntimeArgs` function
- Modify the `TestFlag` function
- Modify the `TestConfigRuntimeArgs` function
- Modify the `Test_killCmd_SendInterrupt_false` function
- Modify the `bytesRead` variable in the `Test_killCmd_SendInterrupt_false` function
also fix https://github.com/cosmtrek/air/pull/439
> refactor: refactor test functions and remove unused variables

- runner/engine.go
- Add a line to close the `e.canExit` channel in the `start` function
main.go
```go
package main
import "log"
func main() {
log.Println("Hello World")
}
```
Unable to terminate the process.
> fix: close the `e.canExit` channel in the `start` function

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/smoke_test.yml
- .github/workflows/smoke_test_reuse_job.yml
- .github/workflows/smoke_test_window_reust_job.yml
- Update the version of `actions/checkout` from `v2` to `v4` in `.github/workflows/build.yml`
- Update the version of `actions/setup-go` from `v2` to `v4` in `.github/workflows/build.yml`
- Update the version of `codecov/codecov-action` from `v2` to `v3` in `.github/workflows/build.yml`
- Update the version of `docker/setup-qemu-action` from `v1` to `v3` in `.github/workflows/build.yml`
- Update the version of `docker/setup-buildx-action` from `v1` to `v3` in `.github/workflows/build.yml`
- Update the version of `docker/login-action` from `v1` to `v3` in `.github/workflows/build.yml`
- Update the version of `docker/build-push-action` from `v2` to `v5` in `.github/workflows/build.yml`
Enable testing in Pull Request event.
> chore: update GitHub Actions versions in build and release workflows

- README.md
Hello,
This allows the user/dev to use `air` in a more practical way in a rootless (while using podman) dev environment.
```
air() {
podman run -it --rm \
-w "$PWD" -v "$PWD":"$PWD" \
-p "$AIR_PORT":"$AIR_PORT" \
docker.io/cosmtrek/air "$@"
}
```
you add this piece of code in .bashrc of example, then run the code:
`AIR_PORT=8080 air init ` > this will create the .air.toml
`AIR_PORT=8080 air -c .ait.toml` this will run the .air.toml created by the init.
> Add Podman/Docker container control like app with function in the shellrc

- README.md
Update installation to use [goblin.run](https://goblin.run)
> Update install section to use goblin.run

- README.md
This PR removes the duplicated `Via go install` section from README.
> docs(readme): remove duplicated section

- .golangci.yml
- Makefile
- hack/check.sh
- main.go
- runner/util_test.go
crurrently when updating `main.go` or by running `hack/check.sh all`
- _errors_ with 
```
main.go:54:1: comment on exported function GetVersionInfo should be of the form "GetVersionInfo ..."
main.go:55:23: exported func GetVersionInfo returns unexported type main.versionInfo, which can be annoying to use
Please fix the errors above :)
```
- noisy - unrelated YAML _wanings_  (`.go` prefix)
```
.goreleaser.yml:2:9: illegal label declaration
.goreleaser.yml:3:7: expected ';', found '-'
.goreleaser.yml:19:2: expected '}', found 'EOF'
...
```
this MR is to confirm
- if like to include  [golangci/golangci-lint](https://github.com/golangci/golangci-lint) in the context of deprecated golint is frozen/deprecated https://github.com/golang/go/issues/38968 
- or keep as is, just update `func …
> Fix liting; use golangci lint

- runner/config.go
- runner/config_test.go
- runner/util_linux.go
- runner/util_unix.go
`kill_delay` is parsed as a Duration ([ref](https://github.com/cosmtrek/air/blob/af962ce3f6f1a048642d5c70f97aa525792b6489/runner/config.go#L55)). When given as an integer (as in the [example config](https://github.om/cosmtrek/air/blob/af962ce3f6f1a048642d5c70f97aa525792b6489/air_example.toml#L44)), it is interpreted as nanoseconds, not milliseconds. The sleep will be too short to allow a program to respond to the interrupt and stop cleanly. This change allows the number to be interpreted as milliseconds.
This change is made to preserve backwards compatibility. If the value is specified as an value under 1 millisecond/1 000 000 nanoseconds, like `500` in the example config, the value will be interpreted as the number of milliseconds. For users who figured out that you may specify the time …
> Interpret value of kill_delay as milliseconds

- air_example.toml
- runner/config.go
- runner/engine.go
- runner/engine_test.go
- runner/proxy.go
- runner/proxy_stream.go
- runner/proxy_stream_test.go
- runner/proxy_test.go
This PR implements what is discussed in this issue: https://github.com/cosmtrek/air/issues/141. I started a new webapp using Go templates and would like to have a live reloading functionality (not just hot reloading when files change). The two possible implementations are with websockets or with server-sent events. I chose the latter because it adds the least amount of complexity and no external dependency is required. I'd like some feedback on the config names (port and app_port, or frontend_port and backend_port?) and whether proxy should be enabled by default or not.
It is quite simple to use, add the proxy config, in my case I added my views containing the go templates on `include_dir`, and access the proxy port, e.g. `http://localhost:8090`.
There are two handlers on the proxy, the …
> Add live proxy feature

- runner/proxy.go
Configures proxy to not follow redirects and return to the client the actual response from the server.
Current proxy solution "follows" redirect responses from the server and makes an additional request rather then returning the redirect response to the client.
Client issues a delete request and the server returns a See Other redirect response. Current proxy solution does not return the response but follows the redirect response, makes another request and then returns that response to the client.
> Fix: Proxy return redirect response

- runner/engine.go
- runner/proxy.go
- runner/proxy_stream.go
- runner/proxy_stream_test.go
- runner/proxy_test.go
I improved the error handling by avoiding log.Fatal as much as possible which doesn't clean up the resources properly (leaving the process and ports open). I couldn't reproduce [this issue](https://github.com/cosmtrek/air/issues/584) with the steps mentioned but after running `go test -v -count=1 -race -run TestProxyStream ./runner` a few times I got some race condition warnings. You can run those tests to validate the new behaviour (with atomic counters and RWMutex) working as expected with no warnings. I also added a CORS wildcard allow asked in another issue.
> fix: fix proxy error handling and race conditions

- .github/workflows/build.yml
- runner/proxy.go
The `make check` linting step failed: https://github.com/cosmtrek/air/actions/runs/9240465156/job/25420774320. The build step running in each PR is broken with `golangci-lint: command not found` issue: https://github.com/cosmtrek/air/actions/runs/9149739894/job/25364966455#step:4:13
> fix: add golangci-lint setup action and fix lint issue

- runner/proxy.go
Based on https://github.com/air-verse/air/pull/604. I found other issues as well, we are missing some returns in case of http internal error responses
> fix: fix proxy unmodified response when body tag is missing

- go.mod
- runner/engine.go
close https://github.com/air-verse/air/issues/534
>  Implement graceful shutdown on Mac 

- README-zh_cn.md
the command from https://github.com/air-verse/air/pull/601/files#diff-69b5e601b7e609160e2aaf43356b857c2c623a1269120d921b923e363e018c88R48 not work.
```bash
> go install github.com/cosmtrek/air@latest
go: downloading github.com/cosmtrek/air v1.52.3
go: github.com/cosmtrek/air@latest: version constraints conflict:
github.com/cosmtrek/air@v1.52.3: parsing go.mod:
module declares its path as: github.com/air-verse/air
but was required as: github.com/cosmtrek/air
```
Should be fixed
> fix README_zh_cn go install command

- runner/proxy.go
This addresses two bugs:
1) The loop could exit with an error condition present and fail to inform the user.
2) On Windows 11, syscall.ECONNREFUSED is not returned. Instead we receive net.OpError with a message similar to:
`unable to reach app: Get "http://localhost:7000/": dial tcp [::1]:7000: connectex: No connection could be made because the target machine actively refused it.`
The Fix:
Since the retry loop is short, we retry until no error happens. If an error does occur, we inform the user.
> fix proxy retry loop

- runner/proxy.go
- runner/proxy_test.go
Hello. I often use tailscale to share development process of web pages with my team. Using tailscale you can create a tunnel from your local machine with a public address such as `machine.id.ts.net` but air always connects to `localhost` so live reload can't work on my teammates browsers.
This pr makes browser reload script connect to web page's host.
It works with `localhost:port` and with regular addresses. It works with both `http` and `https`.
I've ran it on linux firefox, chrome and on macOS safari. Seems to be working all right.
> Use web page address when making request to reload proxy

- runner/engine.go
当我配置stop_on_error=false的时候，如果coding编译失败，就不应该删除之前构建成功的执行文件
> fix the stop_on_error is false configuration does not work

- runner/util_windows.go
Fix #128 
I simply compare `util_windows.go` with `util_unix.go`, and setting `c.Stdout`, `c.Stderr` seems to have resolve this issue.
> Fix color output on Windows

- runner/engine.go
- runner/engine_test.go
Fixes: #350 
Base on: #358 
I don't know, why marked #358 PR as draft?
Just fix code by #358 PR author's comments. then create new PR.
> feat: Make include_file overrule include_ext, fixes: #350, base_on: #358

- air_example.toml
- main.go
- runner/config.go
- runner/logger.go
- runner/util.go
useful if the app being watched has structured outputs that are being piped into subsequent program/s.
> feat: silent flag in .air.toml, suppressing all air prints

- runner/config.go
- runner/config_test.go
- runner/engine_test.go
> Revert "FIX: Support working directories containing whitespace"

- .golangci.yml
- runner/config_test.go
The PR removes unneeded in Go 1.23 `tt := tt` and enables `copyloopvar` linter to detect that in the future. See https://go.dev/blog/loopvar-preview
> refactor: remove unnecessary var copy in for

- .golangci.yml
- runner/flag_test.go
- runner/proxy_test.go
- runner/util_test.go
The PR refactors tests by simplifying asserts: swap actual-expected parameters, use `assert.True`, `assert.False`, `require.Error` etc. Additionally, enables `testifylint` to suggests these in a future.
> refactor: simplify test asserts; enable testifylint

- README.md
I was trying to install the AIR on my fresh new machine with bash, 
and as I am new to bash environment, I didn't knew that we have to source the .profile if I add missing bin path. 
It would be great to make it more clear and newbie friendly instruction.
Hence proposing the changes in documentation for better clarity.
> Update unclear .profile changes in README.md

- runner/config.go
- runner/util.go
- runner/util_test.go
Was trying to use `/tmp/air` as `tmp_dir` but it did not work well. `filepath.Join` simply concatenates both components, resulting in something like `/home/user/myproj/tmp/air`, which is counter-intuitive.
> Handle absolute paths in config

- runner/config.go
This PR should fix #668 #655 and #530
The regular expressions, that are used to determine if files should be excluded, are compiled lazily on first request. This causes different kinds of timing related problems, including panics because multiple goroutines will end up compiling the expressions, while other goroutines may return with data that isn't complete.
> remove a data race by compiling the exclude regexes in the preprocess phase instead

- runner/config.go
- runner/flag.go
This PR fixes #718.
After the v1.61.4 release, the user-specified config is overwritten by default values
This commit introduced a bug: 
https://github.com/air-verse/air/commit/c8498c261b0ad39cebc0131952db299018847d08#diff-19e19f16fa5018b7ad46fc960cdbe0138b0029dac020b42c798a9ff9b8203493R14
---
Initial configuration is updated with command line args:
https://github.com/air-verse/air/blob/master/main.go#L97
but, when `defaultConfig` is used in 
https://github.com/air-verse/air/blob/master/runner/flag.go#L9-L17
all command line values are set to default, effectively overwriting everything from user-specified `.air.toml`.
This PR ensures that only command-line arguments that differ from default values overwrite the config. This is safe since the initial config is based on the default and the …
> fix: default config overwrite

- runner/engine.go
- runner/engine_test.go
This PR attempts to fix #669 by reworking how the killFunc is signalled that a shutdown has been requested.
Instead of reading directly from e.binStopCh (that creates a data race with the writer) it closes on a returned shutdown channel that is used from a new mutexed e.stopBin() func. The shutdown channel takes a channel of int, where the int is the "exit code" passed back to the requestor. It isn't actually the exit code of the process, but a code that can be (and currently is) used to os.Exit the entire process if shutdown failed.
The atomic.Bool change is unrelated to the actual issue, but was required to be able to run the unit tests with -race to detect if there were any races between all the channels and goroutine handling going on in this code.
Reading through the issue list there …
> wait for killfunc completion when shutting down current app

- runner/engine.go
- runner/proxy.go
- runner/proxy.js
- runner/proxy_stream.go
- runner/proxy_stream_test.go
- runner/proxy_test.go
This is a feature that I missed when coming from the Javascript wold.
And, being relatively new to Go, having the build fail and testing the fronted with and old version of the program made me lose a good amount of time before I noticed.
Being new to open source and Go I'm sure that this PR will need more work, so I'll appreciate any feedback.
Thanks in advance.
Example:
> Feature: Show build errors when using proxy

- runner/engine.go
- runner/util.go
- runner/util_test.go
- Fixes incorrect command generation when the binary path contains spaces (issue #666).
- Wraps paths with spaces in quotes to prevent shell splitting.
- Adds OS-specific handling for Windows (uses `& "..."` syntax).
**Changes:**
1. Added `formatPath()` function in `runner/util.go` to:
- Quote absolute paths with spaces.
- Apply Windows-specific syntax when needed.
2. Integrated `formatPath()` into command generation in `runner/engine.go`.
3. Added comprehensive tests in `runner/util_test.go` covering:
- Windows/Unix absolute/relative paths with/without spaces.
- Edge cases (empty path, simple filename).
**Testing:**
- Unit tests verify correct behavior across platforms.
- Manually tested on [Windows 11/macOS 15] with paths containing spaces.
**Notes:**
- This ensures commands like …
> Fix: Properly handle paths with spaces in generated command

- README-ja.md
- README.md
Nice to meet you. I'm a Japanese software engineer who finds air very useful for go development. :)
I've added a Japanese README.
It seems that air is also often used in go development in Japan.
I am not a native speaker of English, but I am a native speaker of Japanese.
I have been careful not to change the meaning of the original text, and have tried to avoid free translation as much as possible.
- Added README-ja.md
- Added a link to README-ja.md to README.md
When translating, I kept the following points in mind:
- Use polite language
- Do not add punctuation at the end of sentences in bullet points
- Do not translate expressions that are likely to be understood in their original English
- This applies to "Pull Request" and "Issue"
-  I thought that Japanese developers using Github …
> Add a README for ja
